Add avroutil and schemaregistry
arquivei/foundationkit pull request #81
Opened 2021-07-21 18:32 UTC by victormn

Avroutil is useful to encode, decode and mock a message in Avro format.

Schemaregistry is useful to manage a avro schema registry repository.

2021-07-21 18:42 UTC, eric-reis approved these changes
Approving with some nits. Linter also suggested some changes.

2021-07-21 18:42 UTC, eric-reis commented on avroutil/encoder.go
> +	// Decode decodes @data, in the wire format, into @output.
Nit: Decode on Encode

2021-07-21 18:42 UTC, eric-reis commented on schemaregistry/implschemaregistry/logging.go
> +// WrapWithLogging wraps @next with a cache layer that stores the result indefinitely
Nit: wrapping with logging that caches =D

2021-07-21 18:49 UTC, andremissaglia requested changes

2021-07-21 18:49 UTC, andremissaglia commented on avroutil/decoder.go
> +func DecodeWireFormatMessage(
This is deprecated, there is no reason to include it in foundationkit.

2021-07-21 18:49 UTC, andremissaglia commented on avroutil/decoder.go
> +func SplitAvroWireFormatMessage(msg []byte) (schemaregistry.ID, []byte, error) {
This is deprecated as well, but I think there are some unit tests that depend on this function. Maybe we can leave this function public for now.

2021-07-23 16:16 UTC, rjfonseca approved these changes

2021-07-23 16:24 UTC, merged